- name: Setup Python and Web Server
  hosts: webservers
  become: yes

  tasks:
    # --- Python installation ---
    - name: Install Python3 (RedHat/CentOS)
      yum:
        name: python3
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Python3 (Debian/Ubuntu)
      apt:
        name: python3
        state: present
      when: ansible_os_family == "Debian"

    - name: Verify Python installation
      command: python3 --version
      register: python_version

    - name: Show Python version
      debug:
        msg: "Installed Python version is {{ python_version.stdout }}"

    # --- Apache installation ---
    - name: Install Apache (Debian/Ubuntu)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache (RedHat/CentOS)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure Apache is running
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes

    - name: Deploy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
